Repository strivedi4u/hacktoberfest2024, pull requests merged in 2024-10, with the labels that each got.

#32 doneAdd detailed description of your changes
  shashank.cpp
Labels: bug, documentation, enhancement, help wanted, good first issue, question, HackOctoberFest, HackOctober, HackOctoberfest24, HackOctober2024, hackoctoberfest accepted, hacktoberfest-accepted

#35 Add detailed description of your changes
  shashank.cs
Labels: bug, documentation, enhancement, help wanted, good first issue, question, HackOctoberFest, HackOctober, HackOctoberfest24, HackOctober2024, hackoctoberfest accepted, hacktoberfest-accepted

#43 Build:#25 Single Page Application
  Build Single Page Application/.gitignore
  Build Single Page Application/README.md
  Build Single Page Application/eslint.config.js
  Build Single Page Application/index.html
  Build Single Page Application/package-lock.json
  Build Single Page Application/package.json
  Build Single Page Application/postcss.config.js
  Build Single Page Application/public/vite.svg
  Build Single Page Application/src/App.tsx
  Build Single Page Application/src/components/Home.tsx
  Build Single Page Application/src/components/Posts.tsx
  Build Single Page Application/src/components/Users.tsx
  Build Single Page Application/src/index.css
  Build Single Page Application/src/main.tsx
  Build Single Page Application/src/vite-env.d.ts
  Build Single Page Application/tailwind.config.js
  Build Single Page Application/tsconfig.app.json
  Build Single Page Application/tsconfig.json
  Build Single Page Application/tsconfig.node.json
  Build Single Page Application/vite.config.ts
Labels: good first issue, HackOctoberFest, HackOctober, HackOctoberfest24, HackOctober2024, hackoctoberfest accepted, hacktoberfest-accepted

#51 Add majorityElement function to find majority element in an array
  MajorityElements.cpp
Labels: good first issue, HackOctoberFest, HackOctober, HackOctoberfest24, HackOctober2024, hackoctoberfest accepted, hacktoberfest-accepted

#49 Create Height of Binary Tree C++ File
  heightOfBinaryTree.cpp
Labels: good first issue, HackOctoberFest, HackOctober, HackOctoberfest24, HackOctober2024, hackoctoberfest accepted, hacktoberfest-accepted

#48 22.Dijkastra Algorithm added #41
  Build Single Page Application/Knapsack.cpp
  DijkastraAlgo.cpp
  LIS.cpp
Labels: good first issue, HackOctoberFest, HackOctober, HackOctoberfest24, HackOctober2024, hackoctoberfest accepted, hacktoberfest-accepted

#47 Latest Calculator
  latest Calculator/index.html
  latest Calculator/script.js
  latest Calculator/styles.css
Labels: good first issue, HackOctoberFest, HackOctober, HackOctoberfest24, HackOctober2024, hackoctoberfest accepted, hacktoberfest-accepted

#70 Create Longest Substring Without Repeating Characters.cpp
  Longest Substring Without Repeating Characters.cpp
Labels: good first issue, HackOctoberFest, HackOctober, HackOctoberfest24, HackOctober2024, hackoctoberfest accepted, hacktoberfest-accepted

#68 Added Floyd-Warshall, Prim’s, KMP, Kruskal’s, and Tarjan’s algorithms
  floyd_warshall_algorithm.cpp
  kmp_string_matching.cpp
  kruskals_algorithm.cpp
  prims_algorithm.c
  tarjans_scc_algorithm.cpp
Labels: good first issue, HackOctoberFest, HackOctober, HackOctoberfest24, HackOctober2024, hackoctoberfest accepted, hacktoberfest-accepted

#67 Branch name
  .vscode/c_cpp_properties.json
  .vscode/launch.json
  .vscode/settings.json
  Build a Basic Web Scraper/news_data.json
  Build a Basic Web Scraper/scrapercode.py
Labels: good first issue, HackOctoberFest, HackOctober, HackOctoberfest24, HackOctober2024, hackoctoberfest accepted, hacktoberfest-accepted

#71 Create Quicksort_Radixsort.cpp
  Quicksort_Radixsort.cpp
Labels: good first issue, HackOctoberFest, HackOctober, HackOctoberfest24, HackOctober2024, hackoctoberfest accepted, hacktoberfest-accepted

#65 [ADD] added solution for first non repeating char problem
  first_non_repeating_char_solved.cpp
Labels: good first issue, HackOctoberFest, HackOctober, HackOctoberfest24, HackOctober2024, hackoctoberfest accepted, hacktoberfest-accepted

#64 [ADD] added optimal solution of majority element problem
  majority_element_optimal_soln.cpp
Labels: good first issue, HackOctoberFest, HackOctober, HackOctoberfest24, HackOctober2024, hackoctoberfest accepted, hacktoberfest-accepted

#62 feat: strong password validation in javascript
  strongPasswordValidation.js
Labels: good first issue, HackOctoberFest, HackOctober, HackOctoberfest24, HackOctober2024, hackoctoberfest accepted, hacktoberfest-accepted

#59 Added Kruskals Algorithm
  Kruskal's_algorithm.cpp
Labels: good first issue, HackOctoberFest, HackOctober, HackOctoberfest24, HackOctober2024, hackoctoberfest accepted, hacktoberfest-accepted

#92 Implemented Kadane's Algorithm in CPP #91
  KadanesAlgoCpp.cpp
Labels: good first issue, HackOctoberFest, HackOctober, HackOctoberfest24, HackOctober2024, hackoctoberfest accepted, hacktoberfest-accepted

#90 Implemented Lexical-Analyzer in C
  Lexical-Analyzer.c
Labels: good first issue, HackOctoberFest, HackOctober, HackOctoberfest24, HackOctober2024, hackoctoberfest accepted, hacktoberfest-accepted

#87 Create DiningPhilospher.c
  DiningPhilospher.c
Labels: good first issue, HackOctoberFest, HackOctober, HackOctoberfest24, HackOctober2024, hackoctoberfest accepted, hacktoberfest-accepted

#85 Added a Travel website
  we travels/.vscode/settings.json
  we travels/css/homestyle.css
  we travels/css/humayu's.css
  we travels/css/indiagate.css
  we travels/css/jama.css
  we travels/css/login-style.css
  we travels/css/loginstyle.css
  we travels/css/qutub.css
  we travels/css/redfort.css
  we travels/css/signstyle.css
  we travels/css/style.css
  we travels/home.html
  we travels/humayun's.html
  we travels/images/bwqutubminar.jpg
  we travels/images/humayun's tomb.jfif
  we travels/images/india gate.webp
  we travels/images/jama masjid.jpg
  we travels/images/login-background.jpg
  we travels/images/qutub minar.jfif
  we travels/images/red fort.webp
  we travels/index.html
  we travels/indiagate.html
  we travels/jama.html
  we travels/js/script.js
  we travels/login-form.php
  we travels/loginpage.html
  we travels/path/to/font-awesome/css/font-awesome.min.css
  we travels/qutub.html
  we travels/redfort.html
  we travels/register.php
  we travels/signup.html
  we travels/signuppage.html
  we travels/signupstyle.css
  we travels/upload.php
Labels: good first issue, HackOctoberFest, HackOctober, HackOctoberfest24, HackOctober2024, hackoctoberfest accepted, hacktoberfest-accepted

#84 add: Bubble_sort
  Bubble_sort.cpp
Labels: good first issue, HackOctoberFest, HackOctober, HackOctoberfest24, HackOctober2024, hackoctoberfest accepted, hacktoberfest-accepted

#95 Added Smart Management System
  Smart Study Management System/Code.py
  Smart Study Management System/details.md
Labels: good first issue, HackOctoberFest, HackOctober, HackOctoberfest24, HackOctober2024, hackoctoberfest accepted, hacktoberfest-accepted

#83 mongodb code added
  MongoDB/.DS_Store
  MongoDB/AGGREGATION PIPELINES/Readme.md
  MongoDB/AGGREGATION PIPELINES/playground-1.mongodb.js
  MongoDB/AGGREGATION PIPELINES/playground-2.mongodb.js
  MongoDB/AGGREGATION PIPELINES/playground-3.mongodb.js
  MongoDB/CRUD OPERATION/Readme.md
  MongoDB/CRUD OPERATION/image/Readme/1719379358319.png
  MongoDB/CRUD OPERATION/image/Readme/1719380029294.png
  MongoDB/CRUD OPERATION/image/Readme/1719380268322.png
  MongoDB/CRUD OPERATION/image/Readme/1719380276068.png
  MongoDB/CRUD OPERATION/image/Readme/1719381589596.png
  MongoDB/CRUD OPERATION/image/Readme/1719382348168.png
  MongoDB/CRUD OPERATION/image/Readme/1719390946099.png
  MongoDB/CRUD OPERATION/image/Readme/1719390966792.png
  MongoDB/CRUD OPERATION/image/Readme/1719390975959.png
  MongoDB/CRUD OPERATION/image/Readme/1719391022904.png
  MongoDB/CRUD OPERATION/image/Readme/1719392637873.png
  MongoDB/CRUD OPERATION/image/Readme/1719392714470.png
  MongoDB/CRUD OPERATION/image/Readme/1719393083118.png
  MongoDB/CRUD OPERATION/image/Readme/1719393312377.png
  MongoDB/CRUD OPERATION/image/Readme/1719474412123.png
  MongoDB/CRUD OPERATION/image/Readme/1719474471694.png
  MongoDB/CRUD OPERATION/image/Readme/1719474825906.png
  MongoDB/CRUD OPERATION/image/Readme/1719475051558.png
  MongoDB/CRUD OPERATION/image/Readme/1719485544868.png
  MongoDB/CRUD OPERATION/image/Readme/1719485555030.png
  MongoDB/CRUD OPERATION/image/Readme/1719485984367.png
  MongoDB/CRUD OPERATION/image/Readme/1719486333976.png
  MongoDB/CRUD OPERATION/image/Readme/1719493869378.png
  MongoDB/CRUD OPERATION/image/Readme/1719494671685.png
  MongoDB/CRUD OPERATION/image/Readme/1719494721254.png
  MongoDB/CRUD OPERATION/image/Readme/1719573544384.png
  MongoDB/CRUD OPERATION/image/Readme/1719574582148.png
  MongoDB/CRUD OPERATION/image/Readme/1719574886385.png
  MongoDB/CRUD OPERATION/image/Readme/1719575028341.png
  MongoDB/CRUD OPERATION/image/Readme/1719575241086.png
  MongoDB/CRUD OPERATION/image/Readme/1719575500020.png
  MongoDB/CRUD OPERATION/image/Readme/1719575869461.png
  MongoDB/CRUD OPERATION/image/Readme/1719576820673.png
  MongoDB/CRUD OPERATION/image/Readme/1719576882974.png
  MongoDB/CRUD OPERATION/image/Readme/1719577468017.png
  MongoDB/CRUD OPERATION/image/Readme/1719577777448.png
  MongoDB/CRUD OPERATION/image/Readme/1719577868717.png
  MongoDB/CRUD OPERATION/image/Readme/1719578008980.png
  MongoDB/CRUD OPERATION/image/Readme/1719578019502.png
  MongoDB/INDEXES /ReadMe.md
  MongoDB/ReadMe.md
  MongoDB/package.json
Labels: good first issue, HackOctoberFest, HackOctober, HackOctoberfest24, HackOctober2024, hackoctoberfest accepted, hacktoberfest-accepted

#73 Solution For Least Recently Used (LRU) Cache implementation
  Cache System Using LRU Algorithm.py
Labels: good first issue, HackOctoberFest, HackOctober, HackOctoberfest24, HackOctober2024, hackoctoberfest accepted, hacktoberfest-accepted

#81 merged
  python/Find Angle MBC.py
  python/Finding the percentage.py
  python/Integers Come In All Sizes.py
  python/List Comprehensions.py
  python/Lists.py
  python/Mod Divmod.py
  python/Nested Lists.py
  python/Polar Coordinates.py
  python/Power - Mod Power.py
  python/Runner-Up Score.py
  python/Triangle Quest 2.py
  python/Triangle Quest.py
  python/Tuples.py
  python/basic data type
Labels: good first issue, HackOctoberFest, HackOctober, HackOctoberfest24, HackOctober2024, hackoctoberfest accepted, hacktoberfest-accepted

#77 rotated_sorted_array
  rotated_sorted_array/rotated_sorted_array.cpp
Labels: good first issue, HackOctoberFest, HackOctober, HackOctoberfest24, HackOctober2024, hackoctoberfest accepted, hacktoberfest-accepted

#75 Create OCR.py
  OCR.py
Labels: good first issue, HackOctoberFest, HackOctober, HackOctoberfest24, HackOctober2024, hackoctoberfest accepted, hacktoberfest-accepted

#74 added morris traversal inorder code
  MorrisInorderTraversal.cpp
Labels: good first issue, HackOctoberFest, HackOctober, HackOctoberfest24, HackOctober2024, hackoctoberfest accepted, hacktoberfest-accepted

#72 Create Dijkstra Algorithm.c
  Dijkstra Algorithm.c
Labels: good first issue, HackOctoberFest, HackOctober, HackOctoberfest24, HackOctober2024, hackoctoberfest accepted, hacktoberfest-accepted

#125 Rename a text file name
  MongoDB/INDEXES/ReadMe.md
Labels: good first issue, HackOctoberFest, HackOctober, HackOctoberfest24, HackOctober2024, hackoctoberfest accepted, hacktoberfest-accepted

#124 feat (age-calculator) : new feature age calculator is added
  age-calculator/app.py
  age-calculator/readme.md
  age-calculator/static/styles.css
  age-calculator/templates/index.html
Labels: good first issue, HackOctoberFest, HackOctober, HackOctoberfest24, HackOctober2024, hackoctoberfest accepted, hacktoberfest-accepted

#119 solar system model using html
  sun_earth_moon.html
Labels: good first issue, HackOctoberFest, HackOctober, HackOctoberfest24, HackOctober2024, hackoctoberfest accepted, hacktoberfest-accepted

#117 Update Code.py
  Smart Study Management System/Code.py
Labels: good first issue, HackOctoberFest, HackOctober, HackOctoberfest24, HackOctober2024, hackoctoberfest accepted, hacktoberfest-accepted

#109 Implemented the Kandanes Algorithm
  KadanesAlgoCpp.cpp
Labels: good first issue, HackOctoberFest, HackOctober, HackOctoberfest24, HackOctober2024, hackoctoberfest accepted, hacktoberfest-accepted

#107 Curated portfolio.html
  portfolio.html
Labels: good first issue, HackOctoberFest, HackOctober, HackOctoberfest24, HackOctober2024, hackoctoberfest accepted, hacktoberfest-accepted

#100 Create Implementing_Kadane's_Algorithm.cpp
  Implementing_Kadane's_Algorithm.cpp
Labels: good first issue, HackOctoberFest, HackOctober, HackOctoberfest24, HackOctober2024, hackoctoberfest accepted, hacktoberfest-accepted

#147 Tuples Error Handling
  python/Tuples.py
Labels: good first issue, HackOctoberFest, HackOctober, HackOctoberfest24, HackOctober2024, hackoctoberfest accepted, hacktoberfest-accepted, hacktoberfest

#144 merge two sorted linked list
  merge sorted list.cpp
Labels: good first issue, HackOctoberFest, HackOctober, HackOctoberfest24, HackOctober2024, hackoctoberfest accepted, hacktoberfest-accepted, hacktoberfest

#140 added tortoise and hare algorithm #104
  a.out
  tortoise_hare.cpp
  valid_paranthesis_problem.cpp
Labels: good first issue, HackOctoberFest, HackOctober, HackOctoberfest24, HackOctober2024, hackoctoberfest accepted, hacktoberfest-accepted, hacktoberfest

#141 Add .cpp extensions to DFS soruce file
  DFS.cpp
Labels: good first issue, HackOctoberFest, HackOctober, HackOctoberfest24, HackOctober2024, hackoctoberfest accepted, hacktoberfest-accepted, hacktoberfest

#137 To Add solution for container with most water
  Book Allocation/soltion.cpp
  Container With Most Water/solution.py
Labels: good first issue, HackOctoberFest, HackOctober, HackOctoberfest24, HackOctober2024, hackoctoberfest accepted, hacktoberfest-accepted, hacktoberfest

#139 Added spriral matrix problem in DSA
  Spiral matrix problem
Labels: good first issue, HackOctoberFest, HackOctober, HackOctoberfest24, HackOctober2024, hackoctoberfest accepted, hacktoberfest-accepted, hacktoberfest

#131 Github CodeSource Full stack Mern App
  MERN Projects/Github CodeSource App/.gitignore
  MERN Projects/Github CodeSource App/backend/controllers/explore.controller.js
  MERN Projects/Github CodeSource App/backend/controllers/user.controller.js
  MERN Projects/Github CodeSource App/backend/routes/explore.route.js
  MERN Projects/Github CodeSource App/backend/routes/user.route.js
  MERN Projects/Github CodeSource App/backend/server.js
  MERN Projects/Github CodeSource App/frontend/.eslintrc.cjs
  MERN Projects/Github CodeSource App/frontend/README.md
  MERN Projects/Github CodeSource App/frontend/index.html
  MERN Projects/Github CodeSource App/frontend/package-lock.json
  MERN Projects/Github CodeSource App/frontend/package.json
  MERN Projects/Github CodeSource App/frontend/postcss.config.js
  MERN Projects/Github CodeSource App/frontend/public/bg.png
  MERN Projects/Github CodeSource App/frontend/public/c++.svg
  MERN Projects/Github CodeSource App/frontend/public/csharp.svg
  MERN Projects/Github CodeSource App/frontend/public/css.svg
  MERN Projects/Github CodeSource App/frontend/public/flutter.svg
  MERN Projects/Github CodeSource App/frontend/public/github.svg
  MERN Projects/Github CodeSource App/frontend/public/go.svg
  MERN Projects/Github CodeSource App/frontend/public/html.svg
  MERN Projects/Github CodeSource App/frontend/public/java.svg
  MERN Projects/Github CodeSource App/frontend/public/javascript.svg
  MERN Projects/Github CodeSource App/frontend/public/logo.png
  MERN Projects/Github CodeSource App/frontend/public/python.svg
  MERN Projects/Github CodeSource App/frontend/public/swift.svg
  MERN Projects/Github CodeSource App/frontend/public/typescript.svg
  MERN Projects/Github CodeSource App/frontend/public/vite.svg
  MERN Projects/Github CodeSource App/frontend/src/App.jsx
  MERN Projects/Github CodeSource App/frontend/src/components/Logout.jsx
  MERN Projects/Github CodeSource App/frontend/src/components/ProfileInfo.jsx
  MERN Projects/Github CodeSource App/frontend/src/components/Repo.jsx
  MERN Projects/Github CodeSource App/frontend/src/components/Repos.jsx
  MERN Projects/Github CodeSource App/frontend/src/components/Search.jsx
  MERN Projects/Github CodeSource App/frontend/src/components/Sidebar.jsx
  MERN Projects/Github CodeSource App/frontend/src/components/SortRepos.jsx
  MERN Projects/Github CodeSource App/frontend/src/components/Spinner.jsx
  MERN Projects/Github CodeSource App/frontend/src/index.css
  MERN Projects/Github CodeSource App/frontend/src/main.jsx
  MERN Projects/Github CodeSource App/frontend/src/pages/ExplorePage.jsx
  MERN Projects/Github CodeSource App/frontend/src/pages/HomePage.jsx
  MERN Projects/Github CodeSource App/frontend/src/pages/LikesPage.jsx
  MERN Projects/Github CodeSource App/frontend/src/pages/LoginPage.jsx
  MERN Projects/Github CodeSource App/frontend/src/pages/SignUpPage.jsx
  MERN Projects/Github CodeSource App/frontend/src/utils/constants.js
  MERN Projects/Github CodeSource App/frontend/src/utils/functions.js
  MERN Projects/Github CodeSource App/frontend/tailwind.config.js
  MERN Projects/Github CodeSource App/frontend/vite.config.js
  MERN Projects/Github CodeSource App/package-lock.json
  MERN Projects/Github CodeSource App/package.json
Labels: good first issue, HackOctoberFest, HackOctober, HackOctoberfest24, HackOctober2024, hackoctoberfest accepted, hacktoberfest-accepted, hacktoberfest

#130 randomQuote.py
  randomQuote.py
Labels: good first issue, HackOctoberFest, HackOctober, HackOctoberfest24, HackOctober2024, hackoctoberfest accepted, hacktoberfest-accepted, hacktoberfest

#277 Arrays Interview questions
  Peak Index in a Mountain Array.cpp
  aggressive_cow.cpp
  panagrap.cpp
  sqrt(x).cpp
Labels: good first issue, HackOctoberFest, HackOctoberfest24, hackoctoberfest accepted, hacktoberfest-accepted, hacktoberfest
